### ISSUE TITLE
ERROR sfdx plugins:install sfpowerkit@latest

### ISSUE THREAD

**Issue by MDBG-NC** [dxatscale/sfpowerkit#739]
Getting this error on every pipeline. 

##[error]Command failed: sfdx plugins:install sfpowerkit@latest
D:\Agent01-Default\_work\_tool\node\12.14.0\x64\node_modules\sfdx-cli\node_modules\@salesforce\kit\lib\env.js:18
    constructor(store = process?.env || {}) {
                                               ^
SyntaxError: Unexpected token '.'

**Comment by Caitlyn-Mills** [comment]
I can't replicate this error, what version of sfdx-cli are you on?

**Comment by MDBG-NC** [comment]
version 7.0.4

**Comment by MDBG-NC** [comment]
but trying to install 7.110.0 it seems

**Comment by MDBG-NC** [comment]
Full log:

Starting: Install SFDX
==============================================================================
Task         : Install SFDX with sfpowerkit
Description  : This plugin installs SFDX CLI, SFPowerkit plugin, Please install this task as the first task before any other tasks in the plugin This task is part of sfpowerscripts.
npm WARN eslint-config-xo@0.35.0 requires a peer of eslint@>=7.20.0 but none is installed. You must install peer dependencies yourself.

+ sfdx-cli@7.110.0
removed 2 packages and updated 11 packages in 65.763s

SFDX CLI Installed
Installing Plugins
[ 'sfpowerkit@latest' ]
Whitelisting Plugins
[ 'sfpowerkit' ]
Installing Plugin sfpowerkit@latest
D:\Agent05-Default\_work\_tool\node\12.14.0\x64\node_modules\sfdx-cli\node_modules\@salesforce\kit\lib\env.js:18
##[error]Command failed: sfdx plugins:install sfpowerkit@latest
D:\Agent05-Default\_work\_tool\node\12.14.0\x64\node_modules\sfdx-cli\node_modules\@salesforce\kit\lib\env.js:18
    constructor(store = process?.env || {}) {
                                               ^

SyntaxError: Unexpected token '.'
    at new Script (vm.js:84:7)
    at NativeCompileCache._moduleCompile (D:\Agent05-Default\_work\_tool\node\12.14.0\x64\node_modules\sfdx-cli\node_modules\v8-compile-cache\v8-compile-cache.js:240:18)
    at Module._compile (D:\Agent05-Default\_work\_tool\node\12.14.0\x64\node_modules\sfdx-cli\node_modules\v8-compile-cache\v8-compile-cache.js:184:36)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (D:\Agent05-Default\_work\_tool\node\12.14.0\x64\node_modules\sfdx-cli\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (D:\Agent05-Default\_work\_tool\node\12.14.0\x64\node_modules\sfdx-cli\node_modules\@salesforce\kit\lib\index.js:25:14)
    at Module._compile (D:\Agent05-Default\_work\_tool\node\12.14.0\x64\node_modules\sfdx-cli\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)

    constructor(store = process?.env || {}) {
                                               ^

SyntaxError: Unexpected token '.'
    at new Script (vm.js:84:7)
    at NativeCompileCache._moduleCompile (D:\Agent05-Default\_work\_tool\node\12.14.0\x64\node_modules\sfdx-cli\node_modules\v8-compile-cache\v8-compile-cache.js:240:18)
    at Module._compile (D:\Agent05-Default\_work\_tool\node\12.14.0\x64\node_modules\sfdx-cli\node_modules\v8-compile-cache\v8-compile-cache.js:184:36)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (D:\Agent05-Default\_work\_tool\node\12.14.0\x64\node_modules\sfdx-cli\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (D:\Agent05-Default\_work\_tool\node\12.14.0\x64\node_modules\sfdx-cli\node_modules\@salesforce\kit\lib\index.js:25:14)
    at Module._compile (D:\Agent05-Default\_work\_tool\node\12.14.0\x64\node_modules\sfdx-cli\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
Finishing: Install SFDX

**Comment by Caitlyn-Mills** [comment]
Can you please try with sfdx version 7.162.0 or above?

**Comment by MDBG-NC** [comment]
I will try and update the yaml to 7.162.0 but I can see in my pipeline task, the installation of sfdx in set to "latest" 
![image](https://user-images.githubusercontent.com/108929673/194227980-717baf2e-1f80-4c00-a65b-080af76ed38a.png)

**Comment by MDBG-NC** [comment]
Hi Caitlyn, 
updating the yaml with new version, made it pass and not throw the error. Thank you

**Comment by Caitlyn-Mills** [comment]
Are you using the sfpowerscipts extension task to install sfdx and sfpowerkit? If you are I would recommend installing sfdx and sfpowerkit directly instead. We no longer support this extension.
